name: DevSecOps WrongSecrets Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # --- ÉTAPE 1 : AUDIT DE SÉCURITÉ (Shift-Left) ---
  security-audit:
    name: 1. Audit & Scan de Secrets
    runs-on: self-hosted
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan avec Gitleaks
        continue-on-error: true
        run: |
          echo "Lancement de l'analyse des secrets cachés..."
          gitleaks detect --verbose --source . --report-path gitleaks-report.json

      - name: Conserver le rapport d'analyse (Objectif du TP)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-security-report
          path: gitleaks-report.json
          retention-days: 7

  # --- ÉTAPE 2 : AUTHENTIFICATION VAULT & DÉPLOIEMENT ---
  build-and-secure:
    name: 2. Récupération Vault & Build
    needs: security-audit
    if: always()
    runs-on: self-hosted
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Connexion à HashiCorp Vault via AppRole
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/wrongsecrets db_password | DB_PASSWORD ;
            secret/data/wrongsecrets api_key | API_KEY

      - name: Vérification de l'injection sécurisée
        run: |
          echo "Vérification des variables récupérées depuis le coffre-fort..."
          if [ -z "$DB_PASSWORD" ]; then
            echo "Échec : Impossible de récupérer le secret de production."
            exit 1
          else
            echo "Succès : Le secret a été injecté en mémoire vive."
            echo "Aperçu masqué de la variable : $DB_PASSWORD"
          fi

      - name: Déploiement sécurisé sur le Nœud 3
        run: |
          echo "Déploiement de l'application WrongSecrets..."
          
          sshpass -p "azerty" ssh -o StrictHostKeyChecking=no root@192.168.1.46 "docker run -d --name wrongsecrets-app -p 8080:8080 -e DB_PASSWORD=$DB_PASSWORD -e API_KEY=$API_KEY jeroenwillemsen/wrongsecrets:latest"
          
          echo "Déploiement terminé. L'application tourne avec les secrets injectés."
